print("<!DOCTYPE html>")
print("<html lang=\"en\">")
print("<head>")
print("	<meta charset=\"UTF-8\">")
print("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
print("	<link rel=\"stylesheet\" href=\"css/index.css\"/>")
print("	<title>My dynamic website</title>")
print("</head>")
print("<body>")
print("	<section class=\"hero-homepage\">")
print("	<h1>Welcome to Webserv</h1>")
print("		<img src=\"img/webserv.png\" alt=\"image de badge 42\"/>")
print("	</section>")
print("</body>")
print("</html>")