# Global configuration
error_log boudin.log;
# access_log bouilloire.log;

# error_page 400 error_pages/global/400.html;
# error_page 403 error_pages/global/403.html;
# error_page 404 error_pages/global/404.html;
# error_page 405 error_pages/global/405.html;
# error_page 500 error_pages/global/500.html;
# error_page 504 error_pages/global/504.html;

client_max_body_size 1000M;

server {
	listen 8081 8084;
	server_name localhost 127.0.1.1 127.0.1.2;
	root www/hannah_montana/;
	client_max_body_size 1M;
	cgi_timeout 3;
	
	error_page 400 pages/error_pages/400.html;
	error_page 403 pages/error_pages/403.html;
	error_page 404 pages/error_pages/404.html;
	error_page 405 pages/error_pages/405.html;
	error_page 413 pages/error_pages/413.html;
	error_page 414 pages/error_pages/414.html;
	error_page 415 pages/error_pages/415.html;
	error_page 500 pages/error_pages/500.html;
	error_page 504 pages/error_pages/504.html;

	location / {
		allow_methods GET POST PUT;
		autoindex off;
		index ./pages/coodkies.php index.php ;
		cgi .php;
	}
	
	location /pages/ {
		allow_methods GET;
		autoindex on;
		cgi .php;
	}

	location /pages/error_pages/ {
		allow_methods GET;
		autoindex on;
	}

	location /pages/script.sh {
		allow_methods POST;
		cgi .sh;
		put_posts /var/posts;
	}

	location /pages/post {
		allow_methods GET POST;
		put_uploads /var/uploads;
		put_posts /var/posts;
		client_max_body_size 20M;
		cgi .php;
	}

	location /pages/redirect-external {
		return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
	}

	location /pages/redirect-internal {
		return 301 /pages/redirected_page.php;
	}

	location /delete-post {
		allow_methods DELETE;
	}
	
	location /kapouet {
		root /assets/img;
		index hannah_montana.jpg;
	}
}

server {
	listen 8082;
	server_name localhost;
	root www/static_website/;
	index index.php index.html;
	client_max_body_size 1M;

	location / {
		allow_methods  DELETE GET POST;
		autoindex off;
	}
}

server {
	listen 8083;
	server_name localhost;
	root www/python_website/;
	index index.py index.html;
	client_max_body_size 1M;
	cgi_languages python;
	allow_methods GET POST;
}
